<?php

namespace ContainerZXricFp;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\OrderCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\OrderCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:order:register', [0 => 'app:order:register'], 'Registers a new order.', false, function () use ($container): \App\Aplication\UseCase\Command\Order\OrderCommand {
            return ($container->privates['App\\Aplication\\UseCase\\Command\\Order\\OrderCommand'] ?? $container->load('getOrderCommandService'));
        });
    }
}
