<?php

namespace ContainerZXricFp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\OrderCommand' shared autowired service.
     *
     * @return \App\Command\OrderCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/OrderCommand.php';

        $container->privates['App\\Command\\OrderCommand'] = $instance = new \App\Command\OrderCommand();

        $instance->setName('app:order:register');
        $instance->setAliases([0 => 'app:order:register']);
        $instance->setDescription('Registers a new order.');

        return $instance;
    }
}
