<?php

namespace ContainerZXricFp;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\OrderCommand' shared autowired service.
     *
     * @return \App\Aplication\UseCase\Command\Order\OrderCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/OrderCommand.php';

        $container->privates['App\\Aplication\\UseCase\\Command\\Order\\OrderCommand'] = $instance = new \App\Aplication\UseCase\Command\Order\OrderCommand();

        $instance->setName('app:order:register');
        $instance->setAliases([0 => 'app:order:register']);
        $instance->setDescription('Registers a new order.');

        return $instance;
    }
}
